# nginx-deployment-and-service.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  # Ensure 3 replicas (pods) of the application are running
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        # Use the official NGINX image
        image: nginx
        ports:
        # The container is listening on port 80
        - containerPort: 80